import { readdirSync, readFileSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

/**
 * The one line that keeps an exported game clean.
 *
 * The runtime ships inside the game; the editor and the filesystem service
 * never do (`editor-kernel` D1). The editor imports the runtime and embeds it
 * as its viewport (D2), so the arrow points one way — and an arrow that points
 * one way is a promise until something checks it.
 *
 * Written as a test rather than left to review because the failure is
 * invisible: an import from `editor/` into `runtime/` compiles, passes every
 * behaviour test, runs perfectly in the editor, and shows up as a shipped game
 * carrying a React panel and a Node service's schemas. By then it is a week of
 * unpicking rather than a one-line correction.
 *
 * It lives in `tests/architecture/` rather than `tests/runtime/` because it is
 * a test *about* the runtime rather than a test *of* it: it reads files off
 * disk, so it belongs to the Node half of the two TypeScript projects
 * (`editor-ui` U4), where `node:fs` exists.
 */

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const RUNTIME = path.join(REPO_ROOT, 'runtime')

/** Throwaway projects the browser suite builds; not source, and not always present. */
const TEST_SCRATCH = path.join(REPO_ROOT, 'tests', '.tmp')

/** Not source: dependencies, build output, tooling, and the junctioned skill library. */
const NOT_SOURCE: ReadonlySet<string> = new Set([
  'node_modules',
  'dist',
  '.git',
  '.claude',
  'playwright-report',
  'test-results',
])

/** Folders the runtime may not reach into, and why each one must not ship. */
const FORBIDDEN = [
  { folder: 'editor', because: 'the editor never ships inside a game' },
  { folder: 'sidecar', because: 'the filesystem service is development-only' },
  { folder: 'scripts', because: 'development entry points never ship' },
  { folder: 'tests', because: 'tests never ship' },
]

function runtimeFiles(directory = RUNTIME): string[] {
  return readdirSync(directory).flatMap((entry) => {
    const absolute = path.join(directory, entry)
    if (statSync(absolute).isDirectory()) return runtimeFiles(absolute)
    return absolute.endsWith('.ts') ? [absolute] : []
  })
}

/** Every TypeScript file in the repo — all four layers, plus the config at the root. */
function kernelFiles(directory = REPO_ROOT): string[] {
  return readdirSync(directory).flatMap((entry) => {
    if (NOT_SOURCE.has(entry)) return []
    const absolute = path.join(directory, entry)
    if (absolute === TEST_SCRATCH) return []
    if (statSync(absolute).isDirectory()) return kernelFiles(absolute)
    return /\.tsx?$/.test(entry) ? [absolute] : []
  })
}

/** Every module specifier in a file, from static imports, re-exports and `import(...)`. */
function importsIn(source: string): string[] {
  const specifiers: string[] = []
  const patterns = [
    /(?:^|\n)\s*(?:import|export)[\s\S]*?from\s*['"]([^'"]+)['"]/g,
    /(?:^|\n)\s*import\s*['"]([^'"]+)['"]/g,
    /\bimport\s*\(\s*['"]([^'"]+)['"]\s*\)/g,
  ]

  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) {
      const specifier = match[1]
      if (specifier !== undefined) specifiers.push(specifier)
    }
  }

  return specifiers
}

describe('the runtime stands on its own', () => {
  const files = runtimeFiles()

  it('has files to check, so a green result means something', () => {
    // Without this, deleting or moving `runtime/` would make every assertion
    // below vacuously true and the suite would go quiet rather than red.
    expect(files.length).toBeGreaterThan(2)
  })

  for (const { folder, because } of FORBIDDEN) {
    it(`never imports from ${folder}/, because ${because}`, () => {
      const offenders: string[] = []

      for (const file of files) {
        for (const specifier of importsIn(readFileSync(file, 'utf8'))) {
          const resolved = specifier.startsWith('.')
            ? path.resolve(path.dirname(file), specifier)
            : path.join(REPO_ROOT, specifier)
          const target = path.relative(REPO_ROOT, resolved).split(/[\\/]/)[0]

          if (target === folder) {
            offenders.push(`${path.relative(REPO_ROOT, file)} imports ${specifier}`)
          }
        }
      }

      expect(offenders).toEqual([])
    })
  }

  it('reaches outside itself only for packages a game would ship with', () => {
    // Not a blanket ban on dependencies — the runtime is allowed to have them —
    // but a list short enough that adding to it is a decision somebody makes on
    // purpose rather than a line that slips in.
    //
    // `virtual:game-systems` is not a package and does not resolve to one: it is
    // generated by `scripts/game-code.ts` from the project folder being built, and
    // it is how a game's own systems reach the thing that runs them. It is allowed
    // past because the alternative is worse in both directions — the runtime
    // importing a game folder outright, or the game's code being reached for by
    // some second path the export does not share. One file names it (`web/main.ts`)
    // and hands the result on as an argument.
    const allowed = new Set(['phaser', 'zod', 'virtual:game-systems'])
    const external = new Set<string>()

    for (const file of files) {
      for (const specifier of importsIn(readFileSync(file, 'utf8'))) {
        if (specifier.startsWith('.')) continue
        external.add(specifier.startsWith('@') ? specifier.split('/').slice(0, 2).join('/') : (specifier.split('/')[0] ?? specifier))
      }
    }

    expect([...external].filter((name) => !allowed.has(name))).toEqual([])
  })
})

/**
 * The kernel is the application; a game folder is a document it opens. The arrow
 * points one way — `games/tower-defense/` imports nothing from here, and nothing
 * here imports from it — and that is what lets one installation open many games,
 * and lets a game folder hold no engine at all.
 *
 * `genre-spinup` predicted this as "one line in boundaries.test.ts": another entry
 * in `FORBIDDEN` above, named `games`. **That line could never have fired**, and
 * the reason generalises. The check above resolves a specifier and takes the first
 * segment of its path *relative to the repo root*; for anything outside the repo
 * that segment is `..`, never a folder name. `games/` is a sibling of this repo,
 * not a folder in it, so it is invisible to a test written that way.
 *
 * So the invariant is stated as what it actually is — **no relative import escapes
 * the repo** — which is stronger than naming one sibling, catches the next sibling
 * nobody has thought of, and holds when `kernel-2d` is cloned somewhere with no
 * `games/` next to it at all. A test that named `games/` would have had to assert
 * the folder exists to avoid W9's vacuous pass, and would then go red for anyone
 * who cloned this repo on its own.
 *
 * It scans all four layers rather than just `runtime/`, because this one is about
 * the repo boundary rather than the shipping boundary: an editor panel reaching
 * into a game folder is the same mistake and would not show up above.
 */
describe('the kernel stays inside its own repo', () => {
  const files = kernelFiles()

  it('has files to check, so a green result means something', () => {
    // W9. The walk starts at the repo root, so a rename cannot quietly empty it —
    // but a bad ignore entry could, and that failure is silent by nature.
    expect(files.length).toBeGreaterThan(50)
  })

  it('never imports from a game folder, or anywhere else outside this repo', () => {
    const offenders: string[] = []

    for (const file of files) {
      for (const specifier of importsIn(readFileSync(file, 'utf8'))) {
        // Package imports are the business of the test above; this one is only
        // about relative paths, which are the only way to walk out of the repo.
        if (!specifier.startsWith('.')) continue

        const resolved = path.resolve(path.dirname(file), specifier)
        if (path.relative(REPO_ROOT, resolved).startsWith('..')) {
          offenders.push(`${path.relative(REPO_ROOT, file)} imports ${specifier}`)
        }
      }
    }

    expect(offenders).toEqual([])
  })
})
