import { systems } from 'virtual:game-systems'

import { startGame, type GameHandle } from './start-game'

/**
 * The page's wiring, and nothing else.
 *
 * Separated from `start-game.ts` so that the game is a function anybody can call
 * with a host element — a genre layer wanting to boot it inside something of its
 * own, a test, a later desktop shell — and the page is the two lines that call it.
 * Everything interesting is next door.
 *
 * **This is where a game's own code joins the game**, and it is the only file in
 * `runtime/` that names the seam. `virtual:game-systems` is not a package: it is
 * generated by `scripts/game-code.ts` from the project folder being built, and it
 * is the one specifier the runtime's import check allows past on purpose. Keeping
 * it here rather than inside `start-game.ts` is what leaves the thing that runs a
 * function of its arguments — the same shape `runLevel` already has, one layer out.
 *
 * The static `systems` rather than `currentSystems()`, because a shipped folder is
 * one build: nothing can edit a system while somebody is playing it. The editor
 * uses the getter, for the reason it has one.
 */

declare global {
  interface Window {
    /**
     * What this game drew, published so it can be asked from outside: by a test
     * comparing an exported folder against the editor, and by anybody with a
     * browser's console open wondering what a folder they were sent is doing.
     *
     * The only global this page defines, and it is read-only.
     */
    kernel2d?: GameHandle
  }
}

const host = document.getElementById('game')

if (host === null) {
  // Only reachable if the page and this file have been edited apart, which is
  // worth a sentence rather than a stack trace: the two ship together.
  document.body.textContent = 'This page has no game element in it, so there is nothing to start.'
} else {
  void startGame(host, systems).then((game) => {
    window.kernel2d = game
  })
}
